#!/bin/bash
# Copyright 2021 Dylan Stephano-Shachter
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ ! -z "${VIRTUAL_ENV}" ]; then
    pip install --upgrade -r requirements-dev.txt > /dev/null
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="lib:src"
else
    export PYTHONPATH="lib:src:$PYTHONPATH"
fi

flake8 || exit $?
if [ "$1" == '--fix' ]; then
    black src tests
    shift
else
    black --diff --check src tests || exit $?
fi
which pytest > /dev/null
if [ $? -eq 0 ]; then
    coverage run --source=src,lib -m pytest -v "$@"
else
    coverage run --source=src,lib -m unittest -v "$@"
fi
coverage report -m
